// <auto-generated />
using CityInfo.API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.API.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20221224233345_AddData")]
    partial class AddData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("CityInfo.API.Models_Entity.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "tehran des",
                            Name = "MS"
                        },
                        new
                        {
                            Id = 2,
                            Description = "tehran des",
                            Name = "LA"
                        },
                        new
                        {
                            Id = 3,
                            Description = "tehran des",
                            Name = "NY"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Models_Entity.PointOfIntrest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointOfIntrest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "",
                            Name = "Cr"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "",
                            Name = "river"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "",
                            Name = "tower"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "",
                            Name = "park"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "",
                            Name = "muse"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "",
                            Name = "manufactur"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Models_Entity.PointOfIntrest", b =>
                {
                    b.HasOne("CityInfo.API.Models_Entity.City", "City")
                        .WithMany("PointOfIntrests")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfo.API.Models_Entity.City", b =>
                {
                    b.Navigation("PointOfIntrests");
                });
#pragma warning restore 612, 618
        }
    }
}
